# Image de base Python
FROM python:3.11-slim
# Définir le répertoire de travail
WORKDIR /app
# Copier le dossier serveur depuis le dossier parent
COPY ../server/ /app/server/
#Exposer le port sur lequel le serveur écoute
EXPOSE 5000
#Lancer le serveur
CMD ["python", "-m", "server.serveur"]